import { CustomCentroids, CustomWiki } from "./models";

/**
 * Domain types that both sides of the boundary speak.
 *
 * These lived in the game's src/models/Interfaces.tsx, which the backend
 * imported across three directory levels; that is what dragged a browser file
 * (and its DOM types) into the backend's compilation and broke its build.
 * Everything here is free of DOM and of library types on purpose.
 */

/** A [longitude, latitude] pair, as GeoJSON orders them. */
export type Position = number[];

/**
 * Geometry of a puzzle piece, as it comes out of ST_AsGeoJSON. Polygon and
 * MultiPolygon both occur, hence the two possible nesting depths.
 */
export interface MultiPolygon {
  type: string;
  coordinates: Position[][] | Position[][][];
}

/** Region grouping used by the puzzle selector, derived from `countries`. */
export interface Regions {
  regionCode: number;
  region: string;
  subregionCode: number;
  subregion: string;
}

/** A puzzle piece: one feature of the map's GeoJSON, plus its custom data. */
export interface PieceProps {
  id?: number;
  geometry: MultiPolygon;
  name: string;
  properties: {
    cartodb_id: number;
    name: string;
    mapcolor: number;
    longitude: number;
    latitude: number;
    /**
     * SVG `viewBox` and path, pre-generated by PostGIS in maps created before
     * the silhouettes were moved to runtime. Only read as a fallback.
     */
    box?: string;
    poly?: string;
  };
  customCentroid?: CustomCentroids;
  customWiki?: CustomWiki;
}

/** Request the editor sends to turn a PostGIS table into a map. */
export interface MapGeneratorModel {
  /** Shapefile layer to read. */
  table: string;
  /** Field holding each piece's id. Empty means number them in name order. */
  id: string;
  /** Field holding each piece's name. Note: the piece's, not the puzzle's. */
  name: string;
  /** Field holding each piece's colour. Empty means use its position. */
  mapColor: string;
  /** Slug for maps/<fileJson>.geojson and the puzzle's URL. */
  fileJson: string;
  /**
   * The puzzle's display name. Optional: without it the slug is un-slugified
   * into one, which turned "zz_prueba_import" into "Zz Prueba Import".
   */
  title?: string;
}

/** A flag file offered by the editor's icon picker. */
export interface FlagsIcons {
  name: string;
  url: string;
}
